# Generated by Django 3.0.5 on 2020-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iver', models.CharField(blank=True, max_length=20)),
                ('product', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
